#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned RP;
typedef unsigned RO;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef U  FlatNodeNum;
typedef U  InstNum;
typedef unsigned long long TimeStamp64;
typedef U  TimeStamp;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef union {
    double I591;
    unsigned long long I592;
    unsigned  I593[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
struct eblk {
    struct eblk * I598;
    E_fn  I599;
    struct iptmpl * I600;
    unsigned I608;
    struct eblk * I609;
};
typedef struct {
    RP  I598;
    RP  I599;
    RP  I600;
    unsigned I608;
    RP  I609;
} RmaEblk;
typedef union {
    double I591;
    unsigned long long I592;
    unsigned  I593[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I629;
    RmaEblk  I597;
    U  I630;
    US  I631 :1;
    US  I632 :4;
    US  I172 :2;
    US  state :2;
    US  I634 :1;
    US  I635 :2;
    US  I636 :2;
    US  fHsim :1;
    US  I637 :1;
    scalar  newval;
    scalar  I639;
    RP  I640;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I619;
    scalar  I620;
    scalar  I621;
    scalar  I622;
    scalar  fHsim :1;
    scalar  I172 :6;
    U  I624;
    EBLK  I625;
    void * I626;
    UP   I627[1];
};
struct RmaMPSched {
    RP  I619;
    scalar  I620;
    scalar  I621;
    scalar  I622;
    scalar  fHsim :1;
    scalar  I172 :6;
    U  I624;
    RmaEblk  I625;
    RP  I626;
    RP   I627[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I619;
    scalar  I620;
    scalar  I621;
    scalar  I622;
    scalar  I172;
    U  I624;
    RmaEblk  I625;
    scalar  I636;
    scalar  I644;
    scalar  I645;
    scalar  I646;
    U  I647;
    RmaClockStruct  I648;
    RmaClockStruct  I649;
    U  state;
    U  I650;
    RP  I600;
    RP  I651;
    RP  I652;
    RP   I627[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I654;
    void * I655;
};
typedef struct {
    RmaEblk  I597;
    RP  I656;
    scalar  I657;
    scalar  I636;
    scalar  I658;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I619;
    scalar  I620;
    scalar  I621;
    scalar  I622;
    scalar  fHsim :1;
    scalar  I172 :6;
    U  I624;
    RmaEblk  I625;
    scalar  I636;
    scalar  I644;
    scalar  I645;
    scalar  I646;
    U  state :4;
    U  I660 :28;
    RmaClockStruct  I648;
    RmaClockStruct  I649;
    RP  I661;
    RP  I600;
    RP  I662;
    RP   I627[1];
};
typedef struct red_t {
    U  I663;
    U  I664;
    U  I665;
} RED;
typedef struct predd {
    PD_e  I172;
    RED   I666[1];
} PREDD;
typedef unsigned long long ULL;
typedef struct {
    RP  I667;
    RP  I651;
    RP  I600;
    RP  I652;
    RmaEblk  I597;
    RmaEblk  I668;
    RP  I669;
    scalar  I657;
    scalar  I636;
    char state;
    uscope_t  I670;
    U  I671;
    RP  I672;
    scalar  I644;
    scalar  I645;
    scalar  I646;
    RmaClockStruct  I648;
    RmaClockStruct  I649;
    RP  I626;
} RmaPulse;
struct etype {
    U  I530 :8;
    U  I531 :24;
    U  I532;
    U  I533 :1;
    U  I534 :1;
    U  I535 :1;
    U  I536 :1;
    U  I537 :1;
    U  I538 :1;
    U  I539 :1;
    U  I540 :1;
    U  I541 :1;
    U  I542 :4;
    U  I543 :1;
    U  I544 :1;
    U  I545 :1;
    U  I546 :1;
    U  I547 :1;
    U  I548 :1;
    U  I549 :1;
    U  I550 :1;
    U  I551 :1;
    U  I552 :1;
    U  I553 :2;
    U  I554 :1;
    U  I555 :6;
    UP  I556;
    U  I557;
    U  I558;
    U  I559 :1;
    U  I560 :1;
    U  I561 :1;
    U  I562 :1;
    U  I563 :2;
    U  I564 :2;
    U  I565 :1;
    U  I566 :1;
    U  I567 :1;
    U  I568 :1;
    U  I569 :1;
    U  I570 :1;
    U  I571 :18;
};
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I673 :1;
    U  I674 :1;
    U  I675 :1;
    U  I676 :1;
    U  I677 :1;
    U  I678 :1;
    U  I679 :1;
    U  I680 :1;
    U  I681 :1;
    U  I682 :1;
    U  I683 :1;
    U  I684 :1;
    U  I685 :1;
    U  I686 :1;
    U  I687 :1;
    U  I688 :1;
    U  I689 :1;
    U  I690 :1;
    U  I691 :1;
    U  I692 :1;
    QIRDModuleType  I693 :2;
    U  I694 :1;
    U  I695 :1;
    U  I696 :1;
    U  I697 :1;
    U  I698 :1;
    U  I699 :1;
    U  I700 :1;
    U  I701 :1;
    U  I702 :1;
    U  I703 :1;
    U  I704 :1;
    U  I705 :1;
    U  I706 :1;
    U  I707 :1;
    U  I708 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    UP  * I20;
    U  I21;
    UP  * I22;
    U  I23;
    U  I24;
    U  I25;
    U  * I26;
    U  * I27;
    void * I28;
    void * I29;
    U  I30;
    int I31;
    UP  I32;
    U  I33;
    U  I34;
    U  I35;
    UP  I36;
    U  * I37;
    BitFlags  I38;
    U  I39;
    U  I40;
    U  I41;
    U  I42;
    U  I43;
    U  * I44;
    U  I45;
    U  * I46;
    U  I47;
    U  I48;
    U  I49;
    U  I50;
    U  I51;
    U  I52;
    U  I53;
    U  * I54;
    U  * I55;
    U  I56;
    U  I57;
    U  * I58;
    U  I59;
    U  * I60;
    U  I61;
    U  I62;
    U  I63;
    U  I64;
    U  * I65;
    U  I66;
    U  * I67;
    U  I68;
    U  I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  * I74;
    char * I75;
    U  I76;
    U  I77;
    U  I78;
    U  I79;
    U  I80;
    U  * I81;
    U  I82;
    U  I83;
    UP  * I84;
    U  I85;
    U  I86;
    UP  * I87;
    U  I88;
    U  I89;
    U  I90;
    U  I91;
    U  I92;
    U  I93;
    U  * I94;
    U  I95;
    U  I96;
    U  * I97;
    U  * I98;
    U  * I99;
    U  * I100;
    U  * I101;
    U  I102;
    U  I103;
    struct taskInfo * I104;
    U  I106;
    U  I107;
    int * I108;
    UP  * I109;
    U  I110;
    U  I111;
    U  I112;
    U  I113;
    U  I114;
    struct qrefer * I115;
    U  * I117;
    unsigned * I118;
    void * I119;
    U  I120;
    U  I121;
    U  I122;
    U  I123;
    U  * I124;
    U  I125;
    U  * I126;
    U  I127;
    U  I128;
    U  I129;
    U  * I130;
    U  I131;
    U  * I132;
    U  I133;
    U  I134;
    U  * I135;
    U  I136;
    U  I137;
    U  * I138;
    U  * I139;
    U  * I140;
    U  I141;
    U  I142;
    U  I143;
    U  I144;
    U  I145;
    struct qrefee * I146;
    U  * I148;
    U  I149;
    struct qdefrefee * I150;
    U  * I152;
    int (* I153)(void);
    char * I154;
    U  I155;
    U  I156;
    void * I157;
    void * I158;
    NumLibs_t  I159;
    char * I160;
    U  * I161;
    U  I162;
    U  I163;
    U  I164;
    U  I165;
    U  I166;
    U  * I167;
    U  * I168;
    int I169;
    struct clock_load * I170;
    int I185;
    struct clock_data * I186;
    int I202;
    struct clock_hiconn * I203;
    U  I207;
    int I208;
    U  I209;
    int I210;
    U  * I211;
    U  * I212;
    U  I213;
    void * I214;
    U  I215;
    U  I216;
    UP  * I217;
    void * I218;
    U  I219;
    UP  * I220;
    U  * I221;
    int (* I222)(void);
    U  * I223;
    UP  * I224;
    U  * I225;
    U  I226 :1;
    U  I227 :31;
    U  I228;
    U  I229;
    UP  * I230;
    U  * I231;
    U  I232 :1;
    U  I233 :1;
    U  I234 :1;
    U  I235 :1;
    U  I236 :28;
    U  I237;
    U  I238;
    U  I239;
    U  I240;
    UP  * I241;
    UP  * I242;
    U  * I243;
    U  * I244;
    UP  * I245;
    UP  * I246;
    UP  * I247;
    U  * I248;
    UP  * I249;
    UP  * I250;
    UP  * I251;
    char * I252;
    U  I253;
    U  I254;
    U  I255;
    UP  * I256;
    UP  * I257;
    UP  * I258;
    UP  * I259;
    UP  * I260;
    UP  * I261;
    UP  * I262;
    UP  * I263;
    UP  * I264;
    UP  * I265;
    U  I266;
    U  I267;
    U  I268;
    U  I269;
    U  I270;
    U  I271;
    U  I272;
    char * I273;
    U  * I274;
    U  I275;
    U  I276;
    U  I277;
    U  I278;
    U  I279;
    U  I280;
    UP  * I281;
    UP  * I282;
    UP  * I283;
    UP  * I284;
    struct daidirInfo * I285;
    struct vcs_tftable * I287;
    U  I289;
    UP  * I290;
    UP  * I291;
    U  I292;
    U  I293;
    U  * I294;
    UP  (* I295)(void);
    UP  (* I296)(void);
    UP  (* I297)(void);
    UP  (* I298)(void);
    UP  (* I299)(void);
    int * I300;
    int (* I301)(void);
    char * I302;
    UP  * I303;
    UP  * I304;
    UP  (* I305)(void);
    int (* I306)(void);
    int * I307;
    int (* I308)(void);
    int * I309;
    char * I310;
    U  * I311;
    U  * I312;
    void * I313;
    void * I314;
    U  I315;
    U  I316;
    U  I317;
    U  I318;
    U  I319;
    U  I320;
    UP  * I321;
    U  * I322;
    U  * I323;
    U  I324 :15;
    U  I325 :14;
    U  I326 :1;
    U  I327 :1;
    U  I328 :1;
    U  I329 :3;
    U  I330 :1;
    U  I331 :1;
    U  I332 :1;
    U  I333 :17;
    U  I334 :3;
    U  I335 :5;
    U  I336 :1;
    struct scope * I337;
    U  I339;
    U  I340;
    U  I341;
    U  * I342;
    U  * I343;
    U  * I344;
    U  I345;
    U  I346;
    U  I347;
    struct pcbt * I348;
    U  I357;
    U  I358;
    U  I359;
    U  I360;
    void * I361;
    void * I362;
    void * I363;
    int I364;
    U  I365;
    U  I366;
    U  I367;
    U  I368;
    U  I369;
    void * I370;
    UP  * I371;
    U  I372;
    U  I373;
    void * I374;
    U  I375;
    void * I376;
    U  I377;
    void * I378;
    U  I379;
    int (* I380)(void);
    int (* I381)(void);
    void * I382;
    void * I383;
    void * I384;
    U  I385;
    U  I386;
    U  I387;
    U  I388;
    U  I389;
    U  I390;
    char * I391;
    U  I392;
    U  * I393;
    U  I394;
    U  * I395;
    U  I396;
    U  I397;
    U  I398;
    U  I399;
    U  I400;
    U  I401;
    U  * I402;
    U  I403;
    U  I404;
    U  * I405;
    U  I406;
    U  * I407;
    char * I408;
    U  I409;
    U  I410;
    U  I411;
    U  I412;
    U  * I413;
    U  I414;
    U  I415;
    struct cosim_info * I416;
    U  I418;
    U  * I419;
    U  I420;
    U  I421;
    U  * I422;
    U  I423;
    U  * I424;
    U  I425;
    U  I426;
    U  * I427;
    U  I428;
    U  * I429;
    U  I430;
    U  I431;
    U  I432;
    U  I433;
    U  I434;
    U  I435;
    U  I436;
    U  I437;
    U  * I438;
    U  * I439;
    void (* I440)(void);
    U  * I441;
    UP  * I442;
    struct mhdl_outInfo * I443;
    UP  * I445;
    U  I446;
    UP  * I447;
    U  I448;
    void * I449;
    U  * I450;
    void * I451;
    U  I452;
    U  I453;
    void * I454;
    void * I455;
    U  * I456;
    U  * I457;
    U  * I458;
    U  * I459;
    void * I460;
    U  I461;
    void * I462;
    U  * I463;
    char * I464;
    int (* I465)(void);
    U  * I466;
    char * I467;
    char * I468;
    U  I469;
    U  * I470;
    struct regInitInfo * I471;
    UP  * I473;
    U  * I474;
    char * I475;
    U  I476;
    U  I477;
    U  I478;
    U  I479;
    U  I480;
    U  I481;
    U  I482;
    U  I483;
    U  * I484;
    U  * I485;
    U  I486;
    U  I487;
    U  I488;
    U  I489;
    UP  * I490;
    U  I491;
    UP  * I492;
    U  I493;
    U  I494;
    U  I495;
    U  * I496;
    U  I497;
    U  I498;
    U  I499;
    U  * I500;
    U  * I501;
    UP  * I502;
    UP  * I503;
    void * I504;
    UP  I505;
    void * I506;
    void * I507;
    void * I508;
    void * I509;
    U  * I510;
    U  * I511;
    void * I512;
    U  I513 :1;
    U  I514 :31;
    U  I515;
    U  I516;
    int I517;
    void * I518;
    UP  * I519;
    UP  I520;
    U  I521;
    char * I522;
    U  * I523;
    U  * I524;
    char * I525;
    int * I526;
    UP  * I527;
    struct etype * I528;
    U  I572;
    U  I573;
    U  * I574;
    U  I575;
    U  * I576;
    U  I577;
    U  I578;
    U  * I579;
};
typedef struct pcbt {
    U  * I350;
    UP  I351;
    U  I352;
    U  I353;
    U  I354;
    U  I355;
    U  I356;
} PCBT;
struct iptmpl {
    QIRD  * I602;
    struct vcs_globals_t * I603;
    void * I605;
    UP  I606;
    UP  I607;
    struct iptmpl * I600[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I741[256];
    struct _hsimPeriodL * I713;
} HsimPeriodL;
typedef struct {
    U   I743[2];
    U  I744 :1;
    U  I745 :1;
    U  I746 :8;
    U  I747 :8;
    U  I748 :8;
    U  I749 :4;
    unsigned long long I750;
    unsigned long long I751;
    unsigned long long I752;
    unsigned long long I753;
    unsigned long long I754;
    U  I755;
    U  I756;
    U  I757;
    U  I758;
    HsimPeriodL  * I759;
    HsimPeriodL  * I760;
    U  I761;
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I762;
    InstNum  I763;
    U  I721;
    scalar  I764;
    UB  I765;
    UB  I766;
    UB  I767;
    U  I768;
    U  I769;
    U  I770;
    U  I771;
    U  I772;
    HsimSignalMonitor  * I773;
    RmaTimeStamp64  I774;
    U  I775;
    RmaTimeStamp64  I776;
} HsimNodeRecord;
typedef struct {
    RP  I777;
    RP  I600;
} RmaIbfIp;
typedef struct {
    RP  I777;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I597;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RmaEblk  I597;
    RP  I778;
    vec32  I779;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I597;
    RP  I778;
    vec32   I635[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I597;
    RP  I778;
    scalar   I780[1];
} RmaAnySchedECg;
typedef struct {
    RP  I781;
} RmaRootCbkCg;
typedef struct {
    RP  I782;
} RmaRootVcdCg;
typedef struct {
    RP  I783;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I597;
    RP  I784;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I595 :30;
    U  I785 :1;
    U  I786 :1;
    vec32  I787;
    U  I788;
    RP  I789;
    RP  I790;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I794;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I582;
    RmaIbfPcode   I794[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I794;
} RmaNetTypeGatherGate;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct {
    U  I5;
    U  iinput;
    RP  I797;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    RP  I797;
} RmaCellStateUpdate;
typedef struct {
    U  I5;
    U  state;
    US  I798;
    US  I714;
    U  * I799;
} RmaCellState;
typedef struct {
    U  iinput;
    RP  I800;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I800;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I597;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I597;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    scalar  I801;
    RmaEblk  I597;
    RP  pcode;
    RP  pfn;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I802;
    RP  I803;
    RP  I804;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I597;
    RP  pcode;
    U  I721;
    U   I588[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I587;
    U  I805;
    U   I806[1];
} RmaDbsedRtlLoads;
typedef struct {
    U  I5;
    RP  I666;
    RmaEblk  I597;
    RmaIbfPcode  I807;
} RmaGateDelay;
typedef struct {
    U  I5;
    union {
        RP  I900;
        RP  I1122;
        RP  I1133;
    } I640;
    RmaIbfPcode  I807;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I808;
    RmaIbfPcode  I807;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I807;
    RmaMps  I809;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I810;
    RmaIbfPcode  I807;
    RmaEblk  I625;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I807;
    RmaMpspNewCsdf  I811;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I811;
    RmaIbfPcode  I807;
} RmaMPPulseOptHybridDelay;
typedef struct {
    U  I5;
    U  I665;
    RmaTransEventHdr  I726;
    RP  I662;
    RmaIbfPcode  I807;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I665;
    RmaEblk  I597;
    RmaIbfPcode  I807;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I597;
    RmaIbfPcode  I807;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I812;
    U  I813;
    RmaTransEventHdr  I726;
    RP  I662;
    RmaIbfPcode  I807;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I812;
    U  I813;
    RmaEblk  I597;
    RmaIbfPcode  I807;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I814;
    RmaTransEventHdr  I726;
    RP  I662;
    RmaIbfPcode  I807;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I814;
    RmaEblk  I597;
    RmaIbfPcode  I807;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I597;
    RmaIbfPcode  I807;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I666;
    RmaEblk  I597;
    RmaIbfPcode  I807;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1122;
        RP  I1133;
    } I640;
    RmaIbfPcode  I807;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I666;
    RmaEblk  I597;
    RmaIbfPcode  I807;
} RmaPortDelay;
typedef struct TableAssign_ {
    struct TableAssign_ * I713;
    struct TableAssign_ * I656;
    U  I5;
    U  iinput;
    RP  ptable;
    RP  I800;
} TableAssign;
typedef struct {
    U  I5;
    RP  I656;
    RP  I816;
} RmaTableAssignList;
typedef struct {
    RP  I817;
} RmaWakeupListCg;
typedef struct {
    U  I818;
    U  I819;
    RmaTimeStamp   I820[1];
} RmaTsArray;
typedef struct {
    RP  I713;
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
} RmaTcCoreSimple;
typedef struct {
    RP  I713;
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
    RP  I830;
} RmaTcCoreConditional;
typedef struct {
    RP  I713;
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
    RP  I830;
    RP  I831;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I713;
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
    RP  I831;
    RP  I832;
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
    RP  I833;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
    RP  I830;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
    RP  I830;
    RP  I831;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
    RP  I831;
    RP  I832;
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I821;
    RP  I594;
    U  I822;
    scalar  I823;
    scalar  I824;
    US  I825 :1;
    US  I826 :1;
    US  I827 :1;
    US  I828 :1;
    US  I829 :1;
    US  I637 :11;
    RP  I830;
    RP  I833;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I834;
    RmaTimeStamp  I835;
    scalar  I836;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I713;
    RP  I834;
    RmaTimeStamp  I835;
    scalar  I836;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I835;
    scalar  I836;
    US  I823;
    RP  I831;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I713;
    RmaTimeStamp  I835;
    scalar  I836;
    US  I823;
    RP  I831;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I831;
    RP  I837;
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I713;
    RP  I831;
    RP  I837;
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I838;
    U  I839;
    FlatNodeNum  I840;
    U  I721;
    U  I841;
    U  I842;
    RmaIbfPcode  I807;
    union {
        scalar  I843;
        vec32  I844;
        scalar  * I845;
        vec32  * I846;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I713;
    RP  I656;
    RP  I847;
} RmaDoublyLinkedListElem;
typedef struct {
    RmaDoublyLinkedListElem  I848;
    RmaIbfPcode  I807;
} RmaSwitchGate;
struct clock_load {
    U  I172 :5;
    U  I173 :12;
    U  I174 :1;
    U  I175 :2;
    U  I176 :1;
    U  I177 :1;
    U  I178 :1;
    U  I179 :9;
    U  I180;
    U  I181;
    void (* pfn)(void * I183, char val);
};
typedef struct clock_data {
    U  I188 :1;
    U  I189 :1;
    U  I190 :1;
    U  I191 :1;
    U  I172 :5;
    U  I173 :12;
    U  I192 :6;
    U  I193 :1;
    U  I175 :2;
    U  I176 :1;
    U  I179 :1;
    U  I194;
    U  I195;
    U  I196;
    U  I180;
    U  I197;
    U  I198;
    U  I199;
    U  I200;
    U  I201;
} HdbsClockData;
struct clock_hiconn {
    U  I205;
    U  I206;
    U  I180;
    U  I175;
};
typedef struct _RmaDaiCg {
    RP  I849;
    RP  I850;
    U  I851;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I849;
    RP  I852;
    RP  I853;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I854;
} RmaDaiOptCg;
struct futq {
    struct futq * I610;
    struct futq * I612;
    RmaEblk  * I613;
    RmaEblk  * I614;
    U  I608;
};
struct sched_table {
    struct futq * I615;
    struct futq I616;
    struct hash_bucket * I617;
};
struct dummyq_struct {
    clock_struct  I855;
    EBLK  * I856;
    EBLK  * I857;
    struct futq * I858;
    struct futq * I859;
    struct sched_table * I860;
    struct millenium * I862;
    EBLK  * I864;
    EBLK  * I865;
    EBLK  * I866;
    EBLK  * I867;
    EBLK  * I868;
    EBLK  * I869;
    EBLK  * I870;
    EBLK  * I871;
    EBLK  * I872;
    EBLK  * I873;
    EBLK  * I874;
    EBLK  * I875;
    EBLK  * I876;
    EBLK  * I877;
    EBLK  * I878;
    MPS  * I879;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I598;
    EBLK  * I880;
    int I881;
    struct _lqueue * I629;
} Queue;
typedef struct {
    EBLK  I883;
    U  I884;
    union {
        void * pHeap;
        Queue  * pList;
    } I584;
    Queue   I885[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   XcvtstrTR[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern FP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern Qhdr  * lvlQueue;
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(UB *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, UB *e);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv,	scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();


#ifdef __cplusplus
extern "C" {
#endif
void  hsM_0_0(UB  * pcode, scalar  val);
void  hsM_0_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_0_2(UB  * pcode);
void  hsM_1_0(UB  * pcode, scalar  val);
void  hsM_1_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_1_2(UB  * pcode);
void  hsM_2_0(UB  * pcode, scalar  val);
void  hsM_2_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_2_2(UB  * pcode);
void  hsM_3_0(UB  * pcode, scalar  val);
void  hsM_3_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_3_2(UB  * pcode);
void  hsM_4_0(UB  * pcode, scalar  val);
void  hsM_4_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_4_2(UB  * pcode);
void  hsM_5_0(UB  * pcode, scalar  val);
void  hsM_5_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_5_2(UB  * pcode);
void  hsM_9_0(UB  * pcode, scalar  val);
void  hsM_10_0(UB  * pcode, scalar  val);
void  hsM_11_0(UB  * pcode, scalar  val);
void  hsM_13_0(UB  * pcode, scalar  val);
void  hsM_19_0(UB  * pcode, scalar  val);
void  hsM_20_0(UB  * pcode, scalar  val);
void  hsM_79_0(UB  * pcode, scalar  val);
void  hsM_79_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_79_2(UB  * pcode);
void  hsM_80_0(UB  * pcode, scalar  val);
void  hsM_80_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_80_2(UB  * pcode);
void  hsM_81_0(UB  * pcode, scalar  val);
void  hsM_81_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_81_2(UB  * pcode);
void  hsM_82_0(UB  * pcode, scalar  val);
void  hsM_82_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_82_2(UB  * pcode);
void  hsM_83_0(UB  * pcode, scalar  val);
void  hsM_83_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_83_2(UB  * pcode);
void  hsM_93_0(UB  * pcode, scalar  val);
void  hsM_94_0(UB  * pcode, scalar  val);
void  hsM_94_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_94_2(UB  * pcode);
void  hsM_95_0(UB  * pcode, scalar  val);
void  hsM_95_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_95_2(UB  * pcode);
void  hsM_96_0(UB  * pcode, scalar  val);
void  hsM_96_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_96_2(UB  * pcode);
void  hsM_97_0(UB  * pcode, scalar  val);
void  hsM_97_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_97_2(UB  * pcode);
void  hsM_98_0(UB  * pcode, scalar  val);
void  hsM_98_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_98_2(UB  * pcode);
void  hsM_99_0(UB  * pcode, scalar  val);
void  hsM_99_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_99_2(UB  * pcode);
void  hsM_99_8(UB  * pcode, scalar  val);
void  hsM_102_0(UB  * pcode, scalar  val);
void  hsM_102_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_102_2(UB  * pcode);
void  hsM_102_5(UB  * pcode, UB  val);
void  hsM_103_0(UB  * pcode, scalar  val);
void  hsM_103_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_103_2(UB  * pcode);
void  hsM_104_0(UB  * pcode, scalar  val);
void  hsM_104_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_104_2(UB  * pcode);
void  hsM_105_0(UB  * pcode, scalar  val);
void  hsM_105_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_105_2(UB  * pcode);
void  hsM_106_0(UB  * pcode, scalar  val);
void  hsM_106_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_106_2(UB  * pcode);
void  hsM_107_0(UB  * pcode, scalar  val);
void  hsM_107_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_107_2(UB  * pcode);
void  hsM_108_0(UB  * pcode, scalar  val);
void  hsM_108_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_108_2(UB  * pcode);
void  hsM_109_0(UB  * pcode, scalar  val);
void  hsM_109_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_109_2(UB  * pcode);
void  hsM_109_5(UB  * pcode, UB  val);
void  hsM_110_0(UB  * pcode, scalar  val);
void  hsM_110_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_110_2(UB  * pcode);
void  hsM_111_0(UB  * pcode, scalar  val);
void  hsM_111_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_111_2(UB  * pcode);
void  hsM_112_0(UB  * pcode, scalar  val);
void  hsM_112_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_112_2(UB  * pcode);
void  hsM_113_0(UB  * pcode, scalar  val);
void  hsM_113_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_113_2(UB  * pcode);
void  hsM_114_0(UB  * pcode, scalar  val);
void  hsM_114_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_114_2(UB  * pcode);
void  hsM_115_0(UB  * pcode, scalar  val);
void  hsM_115_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_115_2(UB  * pcode);
void  hsM_115_8(UB  * pcode, scalar  val);
void  hsM_116_0(UB  * pcode, scalar  val);
void  hsM_116_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_116_2(UB  * pcode);
void  hsM_116_5(UB  * pcode, UB  val);
void  hsM_117_0(UB  * pcode, scalar  val);
void  hsM_117_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_117_2(UB  * pcode);
void  hsM_118_0(UB  * pcode, scalar  val);
void  hsM_118_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_118_2(UB  * pcode);
void  hsM_119_0(UB  * pcode, scalar  val);
void  hsM_119_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_119_2(UB  * pcode);
void  hsM_120_0(UB  * pcode, scalar  val);
void  hsM_120_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_120_2(UB  * pcode);
void  hsM_121_0(UB  * pcode, scalar  val);
void  hsM_121_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_121_2(UB  * pcode);
void  hsM_123_0(UB  * pcode, scalar  val);
void  hsM_123_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_123_2(UB  * pcode);
void  hsM_124_0(UB  * pcode, scalar  val);
void  hsM_124_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_124_2(UB  * pcode);
void  hsM_125_0(UB  * pcode, scalar  val);
void  hsM_125_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_125_2(UB  * pcode);
void  hsM_126_0(UB  * pcode, scalar  val);
void  hsM_126_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_126_2(UB  * pcode);
void  hsM_127_0(UB  * pcode, scalar  val);
void  hsM_127_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_127_2(UB  * pcode);
void  hsM_128_0(UB  * pcode, scalar  val);
void  hsM_128_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_128_2(UB  * pcode);
void  hsM_129_0(UB  * pcode, scalar  val);
void  hsM_129_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_129_2(UB  * pcode);
void  hsM_130_0(UB  * pcode, scalar  val);
void  hsM_130_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_130_2(UB  * pcode);
void  hsM_131_0(UB  * pcode, scalar  val);
void  hsM_131_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_131_2(UB  * pcode);
void  hsM_132_0(UB  * pcode, scalar  val);
void  hsM_132_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_132_2(UB  * pcode);
void  hsM_133_0(UB  * pcode, scalar  val);
void  hsM_133_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_133_2(UB  * pcode);
void  hsM_134_0(UB  * pcode, scalar  val);
void  hsM_134_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_134_2(UB  * pcode);
void  hsM_135_0(UB  * pcode, scalar  val);
void  hsM_135_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_135_2(UB  * pcode);
void  hsM_136_0(UB  * pcode, scalar  val);
void  hsM_136_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_136_2(UB  * pcode);
void  hsM_137_0(UB  * pcode, scalar  val);
void  hsM_137_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_137_2(UB  * pcode);
void  hsM_142_0(UB  * pcode, scalar  val);
void  hsM_142_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_142_2(UB  * pcode);
void  hsM_143_0(UB  * pcode, scalar  val);
void  hsM_143_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_143_2(UB  * pcode);
void  hsM_144_0(UB  * pcode, scalar  val);
void  hsM_144_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_144_2(UB  * pcode);
void  hsM_145_0(UB  * pcode, scalar  val);
void  hsM_145_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_145_2(UB  * pcode);
void  hsM_146_0(UB  * pcode, scalar  val);
void  hsM_146_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_146_2(UB  * pcode);
void  hsM_147_0(UB  * pcode, scalar  val);
void  hsM_147_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_147_2(UB  * pcode);
void  hsM_148_0(UB  * pcode, scalar  val);
void  hsM_148_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_148_2(UB  * pcode);
void  hsM_149_0(UB  * pcode, scalar  val);
void  hsM_149_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_149_2(UB  * pcode);
void  hsM_150_0(UB  * pcode, scalar  val);
void  hsM_150_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_150_2(UB  * pcode);
void  hsM_150_8(UB  * pcode, scalar  val);
void  hsM_151_0(UB  * pcode, scalar  val);
void  hsM_151_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_151_2(UB  * pcode);
void  hsM_152_0(UB  * pcode, scalar  val);
void  hsM_152_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_152_2(UB  * pcode);
void  hsM_152_8(UB  * pcode, scalar  val);
void  hsM_153_0(UB  * pcode, scalar  val);
void  hsM_153_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_153_2(UB  * pcode);
void  hsM_154_0(UB  * pcode, scalar  val);
void  hsM_154_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_154_2(UB  * pcode);
void  hsM_155_0(UB  * pcode, scalar  val);
void  hsM_155_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_155_2(UB  * pcode);
void  hsM_156_0(UB  * pcode, scalar  val);
void  hsM_156_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_156_2(UB  * pcode);
void  hsM_157_0(UB  * pcode, scalar  val);
void  hsM_159_0(UB  * pcode, scalar  val);
void  hsM_160_0(UB  * pcode, scalar  val);
void  hsM_160_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_160_2(UB  * pcode);
void  hsM_162_0(UB  * pcode, scalar  val);
void  hsM_162_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_162_2(UB  * pcode);
void  hsM_163_0(UB  * pcode, scalar  val);
void  hsM_163_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_163_2(UB  * pcode);
void  hsM_164_0(UB  * pcode, scalar  val);
void  hsM_164_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_164_2(UB  * pcode);
void  hsM_165_0(UB  * pcode, scalar  val);
void  hsM_165_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_165_2(UB  * pcode);
void  hsM_166_0(UB  * pcode, scalar  val);
void  hsM_166_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_166_2(UB  * pcode);
void  hsM_167_0(UB  * pcode, scalar  val);
void  hsM_167_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_167_2(UB  * pcode);
void  hsM_168_0(UB  * pcode, scalar  val);
void  hsM_168_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_168_2(UB  * pcode);
void  hsM_169_0(UB  * pcode, scalar  val);
void  hsM_169_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_169_2(UB  * pcode);
void  hsM_170_0(UB  * pcode, scalar  val);
void  hsM_170_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_170_2(UB  * pcode);
void  hsM_173_0(UB  * pcode, scalar  val);
void  hsM_182_0(UB  * pcode, scalar  val);
void  hsM_182_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_182_2(UB  * pcode);
void  hsM_183_0(UB  * pcode, scalar  val);
void  hsM_183_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_183_2(UB  * pcode);
void  hsM_184_0(UB  * pcode, scalar  val);
void  hsM_184_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_184_2(UB  * pcode);
void  hsM_184_8(UB  * pcode, scalar  val);
void  hsM_185_0(UB  * pcode, scalar  val);
void  hsM_185_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_185_2(UB  * pcode);
void  hsM_186_0(UB  * pcode, scalar  val);
void  hsM_186_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_186_2(UB  * pcode);
void  hsM_186_8(UB  * pcode, scalar  val);
void  hsM_187_0(UB  * pcode, scalar  val);
void  hsM_187_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_187_2(UB  * pcode);
void  hsM_187_8(UB  * pcode, scalar  val);
void  hsM_188_0(UB  * pcode, scalar  val);
void  hsM_188_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_188_2(UB  * pcode);
void  hsM_188_8(UB  * pcode, scalar  val);
void  hsM_189_0(UB  * pcode, scalar  val);
void  hsM_189_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_189_2(UB  * pcode);
void  hsM_191_0(UB  * pcode, scalar  val);
void  hsM_191_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_191_2(UB  * pcode);
void  hsM_192_0(UB  * pcode, scalar  val);
void  hsM_192_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_192_2(UB  * pcode);
void  hsM_196_0(UB  * pcode, scalar  val);
void  hsM_196_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_196_2(UB  * pcode);
void  hsM_198_0(UB  * pcode, scalar  val);
void  hsM_198_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_198_2(UB  * pcode);
void  hsM_199_0(UB  * pcode, scalar  val);
void  hsM_199_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_199_2(UB  * pcode);
void  hsM_209_0(UB  * pcode, scalar  val);
void  hsM_209_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_209_2(UB  * pcode);
void  hsM_210_0(UB  * pcode, scalar  val);
void  hsM_210_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_210_2(UB  * pcode);
void  hsM_212_0(UB  * pcode, scalar  val);
void  hsM_212_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_212_2(UB  * pcode);
void  hsM_212_8(UB  * pcode, scalar  val);
void  hsM_213_0(UB  * pcode, scalar  val);
void  hsM_213_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_213_2(UB  * pcode);
void  hsM_216_0(UB  * pcode, scalar  val);
void  hsM_216_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_216_2(UB  * pcode);
void  hsM_217_0(UB  * pcode, scalar  val);
void  hsM_217_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_217_2(UB  * pcode);
void  hsM_218_0(UB  * pcode, scalar  val);
void  hsM_218_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_218_2(UB  * pcode);
void  hsM_219_0(UB  * pcode, scalar  val);
void  hsM_219_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_219_2(UB  * pcode);
void  hsM_220_0(UB  * pcode, scalar  val);
void  hsM_220_1(UB  * pcode, scalar  val, U  I907, scalar  * I906);
void  hsM_220_2(UB  * pcode);
void  hsG_0(struct dummyq_struct * I892, EBLK  * I893, U  I665);
U   hsG_1(U  I905);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

