#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_

#define STDOUT_IS_UARTLITE

#define PLATFORM_EMAC_BASEADDR XPAR_ETHERNET_LITE_BASEADDR

/* Definitions for peripheral FAULTIFY_AXI_WRAPPER_0 */
#define XPAR_FAULTIFY_AXI_WRAPPER_0_BASEADDR 0x75600000
#define XPAR_FAULTIFY_AXI_WRAPPER_0_HIGHADDR 0x7560FFFF

#define PLATFORM_TIMER_BASEADDR XPAR_AXI_TIMER_0_BASEADDR
#define PLATFORM_TIMER_INTERRUPT_INTR XPAR_MICROBLAZE_0_INTC_AXI_TIMER_0_INTERRUPT_INTR
#define PLATFORM_TIMER_INTERRUPT_MASK (1 << XPAR_MICROBLAZE_0_INTC_AXI_TIMER_0_INTERRUPT_INTR)

#ifdef __PPC__
#define CACHEABLE_REGION_MASK 0xffffffff80000800
#endif

#endif
